name: 'Set Repo Secrets and Variables'
description: 'Set GitHub Secrets and Variables to a repository using environment variables'
branding:
  icon: 'shield'
  color: 'purple'
inputs:
  repo-owner:
    description: 'Repository owner (individual or organization)'
    required: true
  repo-name:
    description: 'Repository name'
    required: true
  secrets-from-env:
    description: 'Set secrets from environment variables, the format is "TARGET_SECRET_NAME=ENV_NAME", separated by spaces'
    required: false
    default: ''
  vars-from-env:
    description: 'Set variables from environment variables, the format is "TARGET_SECRET_NAME=ENV_NAME", separated by spaces'
    required: false
    default: ''
  security-token:
    description: 'GitHub Security Token. It is this identity that sets the secrets to the target repository. The scope for Classic PAT should include "repo" and "workflows". For fine-grain PAT, set "actions", "secrets", "variables", "environments" to "read and write" permissions.'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'